### ISSUE TITLE
bug avec les chapitres en .1 etc

### ISSUE THREAD

**Issue by ced1988** [Egsagon/mangue#1]
bonjour le programme fonctionne bien mais pas avec les chapitres se terminent avec une virgule ou un point comme 29.1 etc sinon fonctionnel avec les chapitres normales merci

**Comment by Egsagon** [comment]
Salut, j'ai fait ca avec l'essai gratuit, j'ai plus acces au site donc je peut pas update. Ca a l'air d'être un probleme de selection seulement donc hesite pas à PR si tu sait faire.
